version:  "3.7"

services:
  mlapp:
    container_name: drug_class_app
    image: abrar1s2/drug_class_app:drugClassApp
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile